// =====================================================================
// BlinkyMGalTest -- in-circuit test of the Blinky-M rev 14 sequencer and
// micro-op-decoder GAL22V10 burns on an Arduino Mega 2560. Fuse-compatible
// with the ATF22V10C.
//
//   *** GENERATED by BlinkyGalTestGen from the .pld sources. Do not
//       hand-edit -- regenerate when the PLDs change. ***
//
// All eleven Blinky-M GALs are purely COMBINATIONAL, so this tester needs
// no clocking: for each GAL it sweeps every used input combination, reads
// the OLMC pins, and compares against the design equations taken straight
// from the .pld files (active-low polarity and GND constants already folded
// into the expected pin level). A PASS means the physical chip implements
// the .pld intent.
//
// HARNESS: reuses TTLSim22V10GalTest.ino wiring, with ONE addition --
// GAL pin 17 (previously unwired) must be connected to Mega D34, because
// every Blinky-M GAL drives pin 17 (IDX3 / SRC1 / AMODE1). All GAL inputs
// are driven by the Mega and all OLMC pins are read; no series resistors.
// The nine sequencer burns gate their outputs Hi-Z via BANKEN (pin 11); the
// tester holds BANKEN high for the functional sweep and adds a short Hi-Z
// phase (BANKEN low) to prove the tri-state bank gating. The two UOP burns
// drive their outputs unconditionally (no BANKEN).
//
// Usage: socket ONE chip, open Serial Monitor at 115200, pick a menu key.
// Power down (or press reset) before swapping chips.
// =====================================================================

#include <avr/pgmspace.h>

// ---- harness ---------------------------------------------------------
// GAL input-capable pins (GAL 1..11,13) -> Mega, fixed order. Held LOW
// unless a GAL sweeps them. BANKEN is GAL pin 11 = Mega D50.
const uint8_t IN_CAPABLE[12] = { 53, 51, 49, 47, 45, 43, 41, 39, 37, 52, 50, 23 };
const uint8_t BANKEN_PIN = 50;
const uint8_t SETTLE_US  = 2;     // generous vs a 15-25 ns part

// ---- reporting -------------------------------------------------------
const uint8_t MAX_REPORT = 24;
uint32_t failures, checks;
char vecBuf[24];

// ---- generic per-GAL descriptor (defined before any function so the
// IDE's auto-generated prototypes can see it) -------------------------
struct GalOutput { uint8_t pin; const char *name; const uint8_t *tt; };
struct GalTest {
  const char *name;
  uint8_t  inCount;              // vectors = 1 << inCount
  const uint8_t *inPins;         // Mega drive pin per input bit
  const char *inLegend;          // bit-order legend, printed once
  uint8_t  outCount;
  const GalOutput *outputs;
  bool     hasBanken;
};

void reportFail(const char *vector, const char *sig, bool expected, bool got) {
  failures++;
  if (failures > MAX_REPORT) return;
  Serial.print(F("FAIL ")); Serial.print(vector);
  Serial.print(F("  ")); Serial.print(sig);
  Serial.print(F(": expected ")); Serial.print(expected);
  Serial.print(F(" got ")); Serial.println(got);
}
void check(const char *vector, const char *sig, uint8_t pin, bool expected) {
  bool got = digitalRead(pin);
  checks++;
  if (got != expected) reportFail(vector, sig, expected, got);
}
void summarize(const char *name, unsigned long t0) {
  unsigned long ms = millis() - t0;
  if (failures > MAX_REPORT) {
    Serial.print(F("... and ")); Serial.print(failures - MAX_REPORT);
    Serial.println(F(" more failures not shown."));
  }
  Serial.print(F("Checked ")); Serial.print(checks);
  Serial.print(F(" output values in ")); Serial.print(ms);
  Serial.println(F(" ms."));
  if (failures == 0) {
    Serial.print(F("*** PASS: ")); Serial.print(name);
    Serial.println(F(" matches the .pld design equations. ***"));
  } else {
    Serial.print(F("*** FAIL: ")); Serial.print(failures);
    Serial.println(F(" mismatches. ***"));
  }
}

void idlePins() {                          // safe state for chip swapping
  for (uint8_t k = 0; k < 12; k++) pinMode(IN_CAPABLE[k], INPUT);
  const uint8_t io[10] = { 26,28,30,34,35,33,31,29,27,25 };
  for (uint8_t k = 0; k < 10; k++) pinMode(io[k], INPUT);
}

void beginGal(const GalTest &g) {
  for (uint8_t k = 0; k < 12; k++) { pinMode(IN_CAPABLE[k], OUTPUT); digitalWrite(IN_CAPABLE[k], LOW); }
  for (uint8_t o = 0; o < g.outCount; o++) pinMode(g.outputs[o].pin, INPUT);
  if (g.hasBanken) digitalWrite(BANKEN_PIN, HIGH);   // bank selected
}

bool ttBit(const uint8_t *tt, uint16_t v) {
  return (pgm_read_byte(tt + (v >> 3)) >> (v & 7)) & 1;
}

void hiZPhase(const GalTest &g) {
  digitalWrite(BANKEN_PIN, LOW);                     // deselect bank
  for (uint8_t o = 0; o < g.outCount; o++) pinMode(g.outputs[o].pin, INPUT_PULLUP);
  uint16_t N = (uint16_t)1 << g.inCount;
  uint16_t probes[3] = { 0, (uint16_t)(N - 1), (uint16_t)(N >> 1) };
  for (uint8_t p = 0; p < 3; p++) {
    uint16_t v = probes[p];
    for (uint8_t i = 0; i < g.inCount; i++) digitalWrite(g.inPins[i], (v >> i) & 1);
    delayMicroseconds(SETTLE_US);
    snprintf(vecBuf, sizeof vecBuf, "Hi-Z v=0x%03X", v);
    for (uint8_t o = 0; o < g.outCount; o++)
      check(vecBuf, g.outputs[o].name, g.outputs[o].pin, true);  // pullup -> 1
  }
}

void runGal(const GalTest &g) {
  Serial.print(F("\nTesting ")); Serial.print(g.name);
  Serial.print(F(" -- ")); Serial.print((uint16_t)1 << g.inCount);
  Serial.println(F(" input vectors..."));
  Serial.print(F("  bit order (b0..): ")); Serial.println(g.inLegend);
  beginGal(g);
  failures = 0; checks = 0;
  unsigned long t0 = millis();
  uint16_t N = (uint16_t)1 << g.inCount;
  for (uint16_t v = 0; v < N; v++) {
    for (uint8_t i = 0; i < g.inCount; i++) digitalWrite(g.inPins[i], (v >> i) & 1);
    delayMicroseconds(SETTLE_US);
    snprintf(vecBuf, sizeof vecBuf, "v=0x%03X", v);
    for (uint8_t o = 0; o < g.outCount; o++)
      check(vecBuf, g.outputs[o].name, g.outputs[o].pin, ttBit(g.outputs[o].tt, v));
  }
  if (g.hasBanken) hiZPhase(g);
  summarize(g.name, t0);
  idlePins();
}

// =====================================================================
// Per-GAL generated data
// =====================================================================

// ---- SEQ_ENTRY : 3 swept input(s) -> 7 output(s) ----
// bit order (b0..b2): T0, T1, T2
const uint8_t SEQ_ENTRY_IDX0_TT[] PROGMEM = {
  0x66
};
const uint8_t SEQ_ENTRY_IDX1_TT[] PROGMEM = {
  0x13
};
const uint8_t SEQ_ENTRY_IDX2_TT[] PROGMEM = {
  0x23
};
const uint8_t SEQ_ENTRY_IDX3_TT[] PROGMEM = {
  0x33
};
const uint8_t SEQ_ENTRY_IDX4_TT[] PROGMEM = {
  0xFC
};
const uint8_t SEQ_ENTRY_IDX5_TT[] PROGMEM = {
  0x0F
};
const uint8_t SEQ_ENTRY_TRSTN_TT[] PROGMEM = {
  0x5F
};
const uint8_t SEQ_ENTRY_IN[] = { 39, 37, 52 };
const GalOutput SEQ_ENTRY_OUT[] = {
  { 26, "IDX0", SEQ_ENTRY_IDX0_TT },
  { 28, "IDX1", SEQ_ENTRY_IDX1_TT },
  { 30, "IDX2", SEQ_ENTRY_IDX2_TT },
  { 34, "IDX3", SEQ_ENTRY_IDX3_TT },
  { 35, "IDX4", SEQ_ENTRY_IDX4_TT },
  { 33, "IDX5", SEQ_ENTRY_IDX5_TT },
  { 25, "TRSTN", SEQ_ENTRY_TRSTN_TT }
};
const GalTest SEQ_ENTRY = { "SEQ_ENTRY", 3, SEQ_ENTRY_IN, "T0 T1 T2", 7, SEQ_ENTRY_OUT, true };

// ---- SEQ_CTL : 6 swept input(s) -> 7 output(s) ----
// bit order (b0..b5): OPL0, OPL1, OPL2, T0, T1, T2
const uint8_t SEQ_CTL_IDX0_TT[] PROGMEM = {
  0xC0, 0x70, 0xCC, 0x77, 0xC8, 0x72, 0xCC, 0x77
};
const uint8_t SEQ_CTL_IDX1_TT[] PROGMEM = {
  0x0A, 0x55, 0x57, 0xAA, 0x0A, 0x55, 0x02, 0xAA
};
const uint8_t SEQ_CTL_IDX2_TT[] PROGMEM = {
  0x00, 0xAF, 0xFF, 0x88, 0x00, 0xAA, 0xFF, 0x88
};
const uint8_t SEQ_CTL_IDX3_TT[] PROGMEM = {
  0x00, 0x05, 0x77, 0xBB, 0xAA, 0xAF, 0xFF, 0xBB
};
const uint8_t SEQ_CTL_IDX4_TT[] PROGMEM = {
  0x00, 0xF0, 0x33, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_CTL_IDX5_TT[] PROGMEM = {
  0x00, 0xFF, 0xCC, 0x55, 0x55, 0x00, 0x00, 0x00
};
const uint8_t SEQ_CTL_TRSTN_TT[] PROGMEM = {
  0xFE, 0x0E, 0xFE, 0x0C, 0x54, 0x04, 0x00, 0x00
};
const uint8_t SEQ_CTL_IN[] = { 51, 49, 47, 39, 37, 52 };
const GalOutput SEQ_CTL_OUT[] = {
  { 26, "IDX0", SEQ_CTL_IDX0_TT },
  { 28, "IDX1", SEQ_CTL_IDX1_TT },
  { 30, "IDX2", SEQ_CTL_IDX2_TT },
  { 34, "IDX3", SEQ_CTL_IDX3_TT },
  { 35, "IDX4", SEQ_CTL_IDX4_TT },
  { 33, "IDX5", SEQ_CTL_IDX5_TT },
  { 25, "TRSTN", SEQ_CTL_TRSTN_TT }
};
const GalTest SEQ_CTL = { "SEQ_CTL", 6, SEQ_CTL_IN, "OPL0 OPL1 OPL2 T0 T1 T2", 7, SEQ_CTL_OUT, true };

// ---- SEQ_CTLX : 1 swept input(s) -> 7 output(s) ----
// bit order (b0..b0): T0
const uint8_t SEQ_CTLX_IDX0_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_CTLX_IDX1_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_CTLX_IDX2_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_CTLX_IDX3_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_CTLX_IDX4_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_CTLX_IDX5_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_CTLX_TRSTN_TT[] PROGMEM = {
  0x01
};
const uint8_t SEQ_CTLX_IN[] = { 39 };
const GalOutput SEQ_CTLX_OUT[] = {
  { 26, "IDX0", SEQ_CTLX_IDX0_TT },
  { 28, "IDX1", SEQ_CTLX_IDX1_TT },
  { 30, "IDX2", SEQ_CTLX_IDX2_TT },
  { 34, "IDX3", SEQ_CTLX_IDX3_TT },
  { 35, "IDX4", SEQ_CTLX_IDX4_TT },
  { 33, "IDX5", SEQ_CTLX_IDX5_TT },
  { 25, "TRSTN", SEQ_CTLX_TRSTN_TT }
};
const GalTest SEQ_CTLX = { "SEQ_CTLX", 1, SEQ_CTLX_IN, "T0", 7, SEQ_CTLX_OUT, true };

// ---- SEQ_ALU : 8 swept input(s) -> 7 output(s) ----
// bit order (b0..b7): O0, O1, O2, O3, O4, O5, T0, T1
const uint8_t SEQ_ALU_IDX0_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFE, 0x7F, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0x7F, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_ALU_IDX1_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0xFF, 0xFF, 0xFF,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_ALU_IDX2_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00
};
const uint8_t SEQ_ALU_IDX3_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0x7F, 0xFF, 0xFF,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_ALU_IDX4_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x80, 0x00, 0x00,
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_ALU_IDX5_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00
};
const uint8_t SEQ_ALU_TRSTN_TT[] PROGMEM = {
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0x7F, 0xFF, 0xFF,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_ALU_IN[] = { 51, 49, 47, 45, 43, 41, 39, 37 };
const GalOutput SEQ_ALU_OUT[] = {
  { 26, "IDX0", SEQ_ALU_IDX0_TT },
  { 28, "IDX1", SEQ_ALU_IDX1_TT },
  { 30, "IDX2", SEQ_ALU_IDX2_TT },
  { 34, "IDX3", SEQ_ALU_IDX3_TT },
  { 35, "IDX4", SEQ_ALU_IDX4_TT },
  { 33, "IDX5", SEQ_ALU_IDX5_TT },
  { 25, "TRSTN", SEQ_ALU_TRSTN_TT }
};
const GalTest SEQ_ALU = { "SEQ_ALU", 8, SEQ_ALU_IN, "O0 O1 O2 O3 O4 O5 T0 T1", 7, SEQ_ALU_OUT, true };

// ---- SEQ_MEM : 7 swept input(s) -> 7 output(s) ----
// bit order (b0..b6): OPL0, OPL1, OPL2, OPL3, T0, T1, T2
const uint8_t SEQ_MEM_IDX0_TT[] PROGMEM = {
  0x10, 0xFF, 0xFE, 0xFF, 0x90, 0xFF, 0xB0, 0xFF, 0x03, 0x00, 0xFF, 0xFE,
  0x83, 0x80, 0xB3, 0xB0
};
const uint8_t SEQ_MEM_IDX1_TT[] PROGMEM = {
  0x00, 0x00, 0x66, 0x66, 0x47, 0x44, 0x55, 0x44, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_MEM_IDX2_TT[] PROGMEM = {
  0x00, 0x00, 0x67, 0x00, 0xB9, 0xB9, 0xFF, 0x00, 0x77, 0x77, 0x77, 0x00,
  0xFF, 0xFF, 0xFF, 0x00
};
const uint8_t SEQ_MEM_IDX3_TT[] PROGMEM = {
  0x00, 0x00, 0x67, 0x66, 0x71, 0x71, 0x03, 0x01, 0x03, 0x00, 0x67, 0x66,
  0x73, 0x71, 0x03, 0x01
};
const uint8_t SEQ_MEM_IDX4_TT[] PROGMEM = {
  0x00, 0x00, 0x66, 0x66, 0x88, 0x88, 0xE8, 0xE8, 0x55, 0x55, 0x77, 0x77,
  0xDD, 0xDD, 0xFD, 0xFD
};
const uint8_t SEQ_MEM_IDX5_TT[] PROGMEM = {
  0x00, 0x00, 0x99, 0x99, 0x66, 0x66, 0x9F, 0x9F, 0x00, 0x00, 0x99, 0x99,
  0x66, 0x66, 0x9F, 0x9F
};
const uint8_t SEQ_MEM_TRSTN_TT[] PROGMEM = {
  0xFF, 0xFF, 0xFF, 0xFF, 0x76, 0x77, 0x16, 0x17, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_MEM_IN[] = { 51, 49, 47, 45, 39, 37, 52 };
const GalOutput SEQ_MEM_OUT[] = {
  { 26, "IDX0", SEQ_MEM_IDX0_TT },
  { 28, "IDX1", SEQ_MEM_IDX1_TT },
  { 30, "IDX2", SEQ_MEM_IDX2_TT },
  { 34, "IDX3", SEQ_MEM_IDX3_TT },
  { 35, "IDX4", SEQ_MEM_IDX4_TT },
  { 33, "IDX5", SEQ_MEM_IDX5_TT },
  { 25, "TRSTN", SEQ_MEM_TRSTN_TT }
};
const GalTest SEQ_MEM = { "SEQ_MEM", 7, SEQ_MEM_IN, "OPL0 OPL1 OPL2 OPL3 T0 T1 T2", 7, SEQ_MEM_OUT, true };

// ---- SEQ_STK : 7 swept input(s) -> 7 output(s) ----
// bit order (b0..b6): OPL0, OPL1, OPL2, OPL3, T0, T1, T2
const uint8_t SEQ_STK_IDX0_TT[] PROGMEM = {
  0xFE, 0xF0, 0xCC, 0x11, 0xF0, 0xFA, 0x44, 0xBB, 0xAA, 0x00, 0x44, 0x11,
  0x00, 0xAA, 0x44, 0xBB
};
const uint8_t SEQ_STK_IDX1_TT[] PROGMEM = {
  0x00, 0x2E, 0x3C, 0x00, 0xF0, 0xF3, 0xFF, 0x00, 0x00, 0xEE, 0xFC, 0x00,
  0xF0, 0xF3, 0xFF, 0x00
};
const uint8_t SEQ_STK_IDX2_TT[] PROGMEM = {
  0x00, 0x00, 0x1D, 0x3F, 0x3F, 0x33, 0x00, 0x00, 0xDD, 0x33, 0x1D, 0x3F,
  0xFF, 0x33, 0x00, 0x00
};
const uint8_t SEQ_STK_IDX3_TT[] PROGMEM = {
  0x00, 0x00, 0xC3, 0xFF, 0xFF, 0x44, 0xC4, 0xFF, 0xFF, 0xFF, 0x03, 0xFF,
  0xFF, 0xFF, 0x44, 0xFF
};
const uint8_t SEQ_STK_IDX4_TT[] PROGMEM = {
  0x00, 0xF0, 0xB0, 0xF0, 0x00, 0xFF, 0xBB, 0xFF, 0x00, 0xF0, 0xF0, 0xF0,
  0x00, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_STK_IDX5_TT[] PROGMEM = {
  0x00, 0x00, 0x01, 0xFF, 0x0F, 0x00, 0x55, 0xFF, 0xFF, 0xFF, 0x01, 0xFF,
  0xFF, 0xFF, 0x55, 0xFF
};
const uint8_t SEQ_STK_TRSTN_TT[] PROGMEM = {
  0x5F, 0x5F, 0x4E, 0x5F, 0x5F, 0x00, 0x40, 0x00, 0x5F, 0x5F, 0x00, 0x00,
  0x5F, 0x00, 0x00, 0x00
};
const uint8_t SEQ_STK_IN[] = { 51, 49, 47, 45, 39, 37, 52 };
const GalOutput SEQ_STK_OUT[] = {
  { 26, "IDX0", SEQ_STK_IDX0_TT },
  { 28, "IDX1", SEQ_STK_IDX1_TT },
  { 30, "IDX2", SEQ_STK_IDX2_TT },
  { 34, "IDX3", SEQ_STK_IDX3_TT },
  { 35, "IDX4", SEQ_STK_IDX4_TT },
  { 33, "IDX5", SEQ_STK_IDX5_TT },
  { 25, "TRSTN", SEQ_STK_TRSTN_TT }
};
const GalTest SEQ_STK = { "SEQ_STK", 7, SEQ_STK_IN, "OPL0 OPL1 OPL2 OPL3 T0 T1 T2", 7, SEQ_STK_OUT, true };

// ---- SEQ_SHIFT : 1 swept input(s) -> 7 output(s) ----
// bit order (b0..b0): T0
const uint8_t SEQ_SHIFT_IDX0_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_SHIFT_IDX1_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_SHIFT_IDX2_TT[] PROGMEM = {
  0x00
};
const uint8_t SEQ_SHIFT_IDX3_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_SHIFT_IDX4_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_SHIFT_IDX5_TT[] PROGMEM = {
  0x02
};
const uint8_t SEQ_SHIFT_TRSTN_TT[] PROGMEM = {
  0x01
};
const uint8_t SEQ_SHIFT_IN[] = { 39 };
const GalOutput SEQ_SHIFT_OUT[] = {
  { 26, "IDX0", SEQ_SHIFT_IDX0_TT },
  { 28, "IDX1", SEQ_SHIFT_IDX1_TT },
  { 30, "IDX2", SEQ_SHIFT_IDX2_TT },
  { 34, "IDX3", SEQ_SHIFT_IDX3_TT },
  { 35, "IDX4", SEQ_SHIFT_IDX4_TT },
  { 33, "IDX5", SEQ_SHIFT_IDX5_TT },
  { 25, "TRSTN", SEQ_SHIFT_TRSTN_TT }
};
const GalTest SEQ_SHIFT = { "SEQ_SHIFT", 1, SEQ_SHIFT_IN, "T0", 7, SEQ_SHIFT_OUT, true };

// ---- SEQ_FLOW : 8 swept input(s) -> 7 output(s) ----
// bit order (b0..b7): OPL0, OPL1, OPL2, OPL3, COND, T0, T1, T2
const uint8_t SEQ_FLOW_IDX0_TT[] PROGMEM = {
  0xCC, 0x00, 0xCC, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x00, 0x0F, 0xFF,
  0x55, 0x55, 0x55, 0xFF, 0xCE, 0x02, 0xCE, 0x02, 0x00, 0x00, 0x00, 0x00,
  0x0F, 0x02, 0x0F, 0xFF, 0x55, 0x55, 0x55, 0xFF
};
const uint8_t SEQ_FLOW_IDX1_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x0F, 0x02, 0x0F, 0xFF, 0x0F, 0x00, 0x0F, 0xFF,
  0xCE, 0x02, 0xCE, 0x02, 0x02, 0x02, 0x02, 0x02, 0x00, 0x00, 0x00, 0xFF,
  0x00, 0x00, 0x00, 0xFF, 0xCC, 0x00, 0xCC, 0x00
};
const uint8_t SEQ_FLOW_IDX2_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0xF0, 0xFF, 0xF0, 0x00, 0xF0, 0xFF, 0xF0, 0x00,
  0xFA, 0xFF, 0xFA, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xF0, 0xFF,
  0xF0, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_FLOW_IDX3_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
  0x33, 0x00, 0x33, 0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
  0x33, 0x00, 0x33, 0xFF, 0x33, 0x00, 0x33, 0xFF
};
const uint8_t SEQ_FLOW_IDX4_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0xA8, 0xFD, 0x00, 0x00, 0xA8, 0xFD, 0x00, 0x00,
  0xFD, 0xFD, 0xFD, 0xFD, 0xFD, 0xFD, 0xFD, 0xFD, 0xAA, 0xFF, 0xAA, 0xFF,
  0xAA, 0xFF, 0xAA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};
const uint8_t SEQ_FLOW_IDX5_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00,
  0xCE, 0xFF, 0xCE, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0xFF, 0x02, 0x02,
  0x00, 0xFF, 0x00, 0x00, 0xCC, 0xFF, 0xCC, 0x00
};
const uint8_t SEQ_FLOW_TRSTN_TT[] PROGMEM = {
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0xFF, 0xFF,
  0x33, 0x00, 0x33, 0xFF, 0xAA, 0x00, 0xAA, 0x00, 0xAA, 0x00, 0xAA, 0x00,
  0xAA, 0x00, 0xAA, 0x00, 0x00, 0x00, 0x00, 0x00
};
const uint8_t SEQ_FLOW_IN[] = { 51, 49, 47, 45, 43, 39, 37, 52 };
const GalOutput SEQ_FLOW_OUT[] = {
  { 26, "IDX0", SEQ_FLOW_IDX0_TT },
  { 28, "IDX1", SEQ_FLOW_IDX1_TT },
  { 30, "IDX2", SEQ_FLOW_IDX2_TT },
  { 34, "IDX3", SEQ_FLOW_IDX3_TT },
  { 35, "IDX4", SEQ_FLOW_IDX4_TT },
  { 33, "IDX5", SEQ_FLOW_IDX5_TT },
  { 25, "TRSTN", SEQ_FLOW_TRSTN_TT }
};
const GalTest SEQ_FLOW = { "SEQ_FLOW", 8, SEQ_FLOW_IN, "OPL0 OPL1 OPL2 OPL3 COND T0 T1 T2", 7, SEQ_FLOW_OUT, true };

// ---- SEQ_FRM : 5 swept input(s) -> 7 output(s) ----
// bit order (b0..b4): OPL0, OPL1, T0, T1, T2
const uint8_t SEQ_FRM_IDX0_TT[] PROGMEM = {
  0x00, 0x10, 0x00, 0x10
};
const uint8_t SEQ_FRM_IDX1_TT[] PROGMEM = {
  0xF0, 0x1F, 0x50, 0x1F
};
const uint8_t SEQ_FRM_IDX2_TT[] PROGMEM = {
  0x00, 0xAF, 0xF0, 0xFF
};
const uint8_t SEQ_FRM_IDX3_TT[] PROGMEM = {
  0xF0, 0xA0, 0x05, 0x05
};
const uint8_t SEQ_FRM_IDX4_TT[] PROGMEM = {
  0x00, 0x00, 0xF0, 0xF0
};
const uint8_t SEQ_FRM_IDX5_TT[] PROGMEM = {
  0x00, 0xF0, 0x0F, 0xFF
};
const uint8_t SEQ_FRM_TRSTN_TT[] PROGMEM = {
  0xFF, 0xEF, 0x0F, 0x0F
};
const uint8_t SEQ_FRM_IN[] = { 51, 49, 39, 37, 52 };
const GalOutput SEQ_FRM_OUT[] = {
  { 26, "IDX0", SEQ_FRM_IDX0_TT },
  { 28, "IDX1", SEQ_FRM_IDX1_TT },
  { 30, "IDX2", SEQ_FRM_IDX2_TT },
  { 34, "IDX3", SEQ_FRM_IDX3_TT },
  { 35, "IDX4", SEQ_FRM_IDX4_TT },
  { 33, "IDX5", SEQ_FRM_IDX5_TT },
  { 25, "TRSTN", SEQ_FRM_TRSTN_TT }
};
const GalTest SEQ_FRM = { "SEQ_FRM", 5, SEQ_FRM_IN, "OPL0 OPL1 T0 T1 T2", 7, SEQ_FRM_OUT, true };

// ---- UOPA : 6 swept input(s) -> 10 output(s) ----
// bit order (b0..b5): IDX0, IDX1, IDX2, IDX3, IDX4, IDX5
const uint8_t UOPA_DST3_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0xF8, 0xFF, 0xFF, 0xFF
};
const uint8_t UOPA_ALUFN1_TT[] PROGMEM = {
  0x00, 0x00, 0x08, 0x02, 0x89, 0x02, 0x00, 0x02
};
const uint8_t UOPA_DST2_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0xFE, 0x07, 0x00, 0xF8, 0xFB
};
const uint8_t UOPA_SRC1_TT[] PROGMEM = {
  0x30, 0x00, 0x00, 0x24, 0x42, 0x75, 0x02, 0x34
};
const uint8_t UOPA_DST0_TT[] PROGMEM = {
  0xF8, 0xC3, 0xFF, 0x71, 0x24, 0x00, 0xF4, 0x71
};
const uint8_t UOPA_SRC0_TT[] PROGMEM = {
  0x40, 0x00, 0x0F, 0x36, 0x89, 0x4A, 0x01, 0x7A
};
const uint8_t UOPA_DST1_TT[] PROGMEM = {
  0x00, 0xFC, 0xFF, 0x81, 0xC7, 0xFF, 0xF7, 0x81
};
const uint8_t UOPA_SRC2_TT[] PROGMEM = {
  0x40, 0x00, 0x00, 0x24, 0x00, 0x80, 0x03, 0xA4
};
const uint8_t UOPA_ALUFN0_TT[] PROGMEM = {
  0x00, 0x00, 0x04, 0x10, 0x09, 0x08, 0x00, 0x10
};
const uint8_t UOPA_ISET_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x20, 0x24
};
const uint8_t UOPA_IN[] = { 51, 49, 47, 45, 43, 41 };
const GalOutput UOPA_OUT[] = {
  { 26, "DST3", UOPA_DST3_TT },
  { 28, "ALUFN1", UOPA_ALUFN1_TT },
  { 30, "DST2", UOPA_DST2_TT },
  { 34, "SRC1", UOPA_SRC1_TT },
  { 35, "DST0", UOPA_DST0_TT },
  { 33, "SRC0", UOPA_SRC0_TT },
  { 31, "DST1", UOPA_DST1_TT },
  { 29, "SRC2", UOPA_SRC2_TT },
  { 27, "ALUFN0", UOPA_ALUFN0_TT },
  { 25, "ISET", UOPA_ISET_TT }
};
const GalTest UOPA = { "UOPA", 6, UOPA_IN, "IDX0 IDX1 IDX2 IDX3 IDX4 IDX5", 10, UOPA_OUT, false };

// ---- UOPB : 6 swept input(s) -> 10 output(s) ----
// bit order (b0..b5): IDX0, IDX1, IDX2, IDX3, IDX4, IDX5
const uint8_t UOPB_SPOP2_TT[] PROGMEM = {
  0x04, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x20
};
const uint8_t UOPB_NZ_WE_TT[] PROGMEM = {
  0x00, 0x00, 0x03, 0x00, 0x20, 0x00, 0xC0, 0xC0
};
const uint8_t UOPB_SPOP1_TT[] PROGMEM = {
  0x22, 0x22, 0x00, 0x01, 0x40, 0x05, 0x01, 0x00
};
const uint8_t UOPB_AMODE1_TT[] PROGMEM = {
  0x00, 0x00, 0x30, 0x40, 0x90, 0x87, 0x01, 0x40
};
const uint8_t UOPB_AMODE0_TT[] PROGMEM = {
  0x70, 0x80, 0xAF, 0x3F, 0x5B, 0x66, 0xED, 0xFF
};
const uint8_t UOPB_AMODE2_TT[] PROGMEM = {
  0x80, 0x3B, 0xC0, 0x49, 0x10, 0xF8, 0x01, 0xF8
};
const uint8_t UOPB_SPOP0_TT[] PROGMEM = {
  0x00, 0x11, 0x00, 0x01, 0x00, 0x38, 0x01, 0x38
};
const uint8_t UOPB_C_WE_TT[] PROGMEM = {
  0x00, 0x00, 0x02, 0x00, 0x20, 0x00, 0x80, 0xFF
};
const uint8_t UOPB_AMODE3_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x02, 0x02
};
const uint8_t UOPB_TOSSH_TT[] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
const uint8_t UOPB_IN[] = { 51, 49, 47, 45, 43, 41 };
const GalOutput UOPB_OUT[] = {
  { 26, "SPOP2", UOPB_SPOP2_TT },
  { 28, "NZ_WE", UOPB_NZ_WE_TT },
  { 30, "SPOP1", UOPB_SPOP1_TT },
  { 34, "AMODE1", UOPB_AMODE1_TT },
  { 35, "AMODE0", UOPB_AMODE0_TT },
  { 33, "AMODE2", UOPB_AMODE2_TT },
  { 31, "SPOP0", UOPB_SPOP0_TT },
  { 29, "C_WE", UOPB_C_WE_TT },
  { 27, "AMODE3", UOPB_AMODE3_TT },
  { 25, "TOSSH", UOPB_TOSSH_TT }
};
const GalTest UOPB = { "UOPB", 6, UOPB_IN, "IDX0 IDX1 IDX2 IDX3 IDX4 IDX5", 10, UOPB_OUT, false };

// =====================================================================
// Menu / dispatch
// =====================================================================
const GalTest *const TESTS[] = { &SEQ_ENTRY, &SEQ_CTL, &SEQ_CTLX, &SEQ_ALU, &SEQ_MEM, &SEQ_STK, &SEQ_SHIFT, &SEQ_FLOW, &SEQ_FRM, &UOPA, &UOPB };
const char SELECT[] = "123456789AB";
const uint8_t NTESTS = 11;

void printMenu() {
  Serial.println(F("\n=============================================="));
  Serial.println(F("Blinky-M rev 14 GAL burn tester"));
  Serial.println(F("Socket ONE chip FIRST, then choose:"));
  Serial.println(F("  1 = SEQ_ENTRY"));
  Serial.println(F("  2 = SEQ_CTL"));
  Serial.println(F("  3 = SEQ_CTLX"));
  Serial.println(F("  4 = SEQ_ALU"));
  Serial.println(F("  5 = SEQ_MEM"));
  Serial.println(F("  6 = SEQ_STK"));
  Serial.println(F("  7 = SEQ_SHIFT"));
  Serial.println(F("  8 = SEQ_FLOW"));
  Serial.println(F("  9 = SEQ_FRM"));
  Serial.println(F("  A = UOPA"));
  Serial.println(F("  B = UOPB"));
  Serial.println(F("  * = run every test in sequence"));
  Serial.println(F("(power down or reset before swapping chips)"));
  Serial.println(F("=============================================="));
}

void setup() {
  Serial.begin(115200);
  idlePins();
  printMenu();
}

void loop() {
  if (!Serial.available()) return;
  char ch = Serial.read();
  if (ch >= 'a' && ch <= 'z') ch -= 32;   // accept lower-case keys
  if (ch == '*') { for (uint8_t i = 0; i < NTESTS; i++) runGal(*TESTS[i]); printMenu(); return; }
  for (uint8_t i = 0; i < NTESTS; i++) {
    if (ch == SELECT[i]) { runGal(*TESTS[i]); printMenu(); return; }
  }
  if (ch > ' ') { Serial.println(F("Unknown key.")); printMenu(); }
}
