using System.Text;

namespace BlinkyMGen;

// ---------------------------------------------------------------------------
// Emits OpcodeTable.cs — a C# source file BlinkyASM references directly, so the
// assembler's opcode map is generated from the same instruction table as the
// control logic and can never drift. Includes the named ALU ops plus the
// general ALU #n form (raw 6-bit '181 function).
// ---------------------------------------------------------------------------

public static class AsmTableEmitter
{
    public static void Emit(string path, IReadOnlyList<Instruction> program)
    {
        var sb = new StringBuilder();
        sb.Append("""
            // OpcodeTable.cs — GENERATED by BlinkyMGen. Do not hand-edit; regenerate.
            //
            // The rev 14 opcode map for BlinkyASM: mnemonic -> opcode + operand shape.
            // The ALU family also accepts the general form  ALU #n  where n is the raw
            // 6-bit '181 function (M CN S3 S2 S1 S0), and  ALU M,CN,Ssss  as an alias.

            using System.Collections.Generic;

            namespace BlinkyM.Assembler;

            public enum OperandShape { None, Imm8, Port8, Count8, Offset8, Addr16 }

            public readonly record struct OpcodeEntry(
                string Mnemonic, byte Opcode, OperandShape Shape, byte Length);

            public static class OpcodeTable
            {
                public static readonly IReadOnlyList<OpcodeEntry> Entries = new OpcodeEntry[]
                {

            """);

        foreach (var ins in program.Where(i => !i.Mnemonic.StartsWith("ALU_")))
        {
            string shape = ins.Operand switch
            {
                OperandShape.None => "OperandShape.None",
                OperandShape.Imm => "OperandShape.Imm8",
                OperandShape.Port => "OperandShape.Port8",
                OperandShape.Count => "OperandShape.Count8",
                OperandShape.Offset => "OperandShape.Offset8",
                OperandShape.Addr => "OperandShape.Addr16",
                _ => "OperandShape.None"
            };
            sb.AppendLine($"        new(\"{ins.Mnemonic}\", 0x{ins.Opcode:X2}, {shape}, {ins.Length}),");
        }

        sb.Append("""
                };

                // The ALU quadrant: opcode = 0x40 | (M<<5) | (CN<<4) | S[3:0].
                // Every one of the 64 codes is a valid instruction. Named ops appear
                // in Entries above; ALU #n reaches the rest.
                public const byte AluQuadrantBase = 0x40;
                public const byte AluQuadrantEnd  = 0x7F;

                public static byte AluOpcode(bool m, bool cn, int s4)
                    => (byte)(AluQuadrantBase | (m ? 0x20 : 0) | (cn ? 0x10 : 0) | (s4 & 0xF));

                // ALU #n where n is the raw 6-bit function in the low six bits.
                public static byte AluOpcodeRaw(int fn6)
                    => (byte)(AluQuadrantBase | (fn6 & 0x3F));

                public static bool IsAluQuadrant(byte opcode)
                    => opcode >= AluQuadrantBase && opcode <= AluQuadrantEnd;
            }

            """);

        File.WriteAllText(path, sb.ToString());
    }
}
