// OpcodeTable.cs — GENERATED by BlinkyMGen. Do not hand-edit; regenerate.
//
// The rev 14 opcode map for BlinkyASM: mnemonic -> opcode + operand shape.
// The ALU family also accepts the general form  ALU #n  where n is the raw
// 6-bit '181 function (M CN S3 S2 S1 S0), and  ALU M,CN,Ssss  as an alias.

namespace BlinkyM.Assembler;

public enum OperandShape { None, Imm8, Port8, Count8, Offset8, Addr16 }

public readonly record struct OpcodeEntry(
    string Mnemonic, byte Opcode, OperandShape Shape, byte Length);

public static class OpcodeTable
{
    public static readonly IReadOnlyList<OpcodeEntry> Entries = new OpcodeEntry[]
    {
        new("NOP", 0x00, OperandShape.None, 1),
        new("RET", 0x01, OperandShape.None, 1),
        new("BRK", 0x02, OperandShape.None, 1),
        new("RTI", 0x03, OperandShape.None, 1),
        new("CLI", 0x04, OperandShape.None, 1),
        new("SEI", 0x05, OperandShape.None, 1),
        new("SHL", 0x10, OperandShape.None, 1),
        new("SHR", 0x11, OperandShape.None, 1),
        new("ASR", 0x13, OperandShape.None, 1),
        new("ROL", 0x14, OperandShape.None, 1),
        new("ROR", 0x15, OperandShape.None, 1),
        new("DUP", 0x20, OperandShape.None, 1),
        new("OVER", 0x21, OperandShape.None, 1),
        new("TUCK", 0x22, OperandShape.None, 1),
        new("SWAP", 0x23, OperandShape.None, 1),
        new("DROP", 0x24, OperandShape.None, 1),
        new("NIP", 0x25, OperandShape.None, 1),
        new("ROT", 0x26, OperandShape.None, 1),
        new(">R", 0x28, OperandShape.None, 1),
        new("R>", 0x29, OperandShape.None, 1),
        new("R@", 0x2A, OperandShape.None, 1),
        new("PUSH", 0x30, OperandShape.Imm8, 2),
        new("LOAD", 0x31, OperandShape.Addr16, 3),
        new("STORE", 0x32, OperandShape.Addr16, 3),
        new("FETCH", 0x33, OperandShape.None, 1),
        new("STORE!", 0x34, OperandShape.None, 1),
        new("IN", 0x35, OperandShape.Port8, 2),
        new("OUT", 0x36, OperandShape.Port8, 2),
        new("INS", 0x37, OperandShape.None, 1),
        new("OUTS", 0x38, OperandShape.None, 1),
        new("ADD", 0x49, OperandShape.None, 1),
        new("SUB", 0x56, OperandShape.None, 1),
        new("ADC", 0x59, OperandShape.None, 1),
        new("NOT", 0x60, OperandShape.None, 1),
        new("XOR", 0x66, OperandShape.None, 1),
        new("AND", 0x6B, OperandShape.None, 1),
        new("OR", 0x6E, OperandShape.None, 1),
        new("TST", 0x6F, OperandShape.None, 1),
        new("ENTER", 0x80, OperandShape.Count8, 2),
        new("LOCAL@", 0x81, OperandShape.Offset8, 2),
        new("LOCAL!", 0x82, OperandShape.Offset8, 2),
        new("JUMP", 0x90, OperandShape.Addr16, 3),
        new("CALL", 0x91, OperandShape.Addr16, 3),
        new("CMP", 0x96, OperandShape.None, 1),
        new("BEQ", 0x9A, OperandShape.Addr16, 3),
        new("BNE", 0x9B, OperandShape.Addr16, 3),
        new("BCS", 0x9C, OperandShape.Addr16, 3),
        new("BCC", 0x9D, OperandShape.Addr16, 3),
        new("BMI", 0x9E, OperandShape.Addr16, 3),
        new("BPL", 0x9F, OperandShape.Addr16, 3),
        new("HALT", 0xFF, OperandShape.None, 1),
    };

    // The ALU quadrant: opcode = 0x40 | (M<<5) | (CN<<4) | S[3:0].
    // Every one of the 64 codes is a valid instruction. Named ops appear
    // in Entries above; ALU #n reaches the rest.
    public const byte AluQuadrantBase = 0x40;
    public const byte AluQuadrantEnd  = 0x7F;

    public static byte AluOpcode(bool m, bool cn, int s4)
        => (byte)(AluQuadrantBase | (m ? 0x20 : 0) | (cn ? 0x10 : 0) | (s4 & 0xF));

    // ALU #n where n is the raw 6-bit function in the low six bits.
    public static byte AluOpcodeRaw(int fn6)
        => (byte)(AluQuadrantBase | (fn6 & 0x3F));

    public static bool IsAluQuadrant(byte opcode)
        => opcode >= AluQuadrantBase && opcode <= AluQuadrantEnd;
}
