using System.Text;

namespace BlinkyMGen;

// ---------------------------------------------------------------------------
// Emits a single self-contained HTML file with three views of rev 14 control:
//   1. Dictionary   — the 57 micro-ops x their 20 decoder lines (Stage 2)
//   2. Sequencer    — per family, (opcode-low, T, COND) -> index (Stage 1)
//   3. Instructions — each opcode as its ordered micro-op sequence (the bridge)
// No JavaScript; styling only.
// ---------------------------------------------------------------------------

public static class HtmlMatrix
{
    public static void Emit(string path, IReadOnlyList<Instruction> program,
                            MicroDictionary dict, Sequencer seq)
    {
        var sb = new StringBuilder();
        sb.Append(Head());
        sb.Append($"<h1>Blinky-M rev 14 &mdash; Control Reference</h1>\n");
        sb.Append($"<div class=sub>Two-stage GAL control &middot; {dict.Count} micro-ops of {MicroDictionary.Slots} &middot; generated by BlinkyMGen</div>\n");

        DictionaryView(sb, dict);
        SequencerView(sb, seq, dict);
        InstructionView(sb, program, dict);

        sb.Append("</body></html>\n");
        File.WriteAllText(path, sb.ToString());
    }

    // View 1 -----------------------------------------------------------------
    static void DictionaryView(StringBuilder sb, MicroDictionary dict)
    {
        sb.Append("<h2>1 &middot; Micro-op dictionary (Stage 2 decode)</h2>\n");
        sb.Append("<p class=note>Each row is one micro-op; a filled cell means that decoder line is asserted. This is the content the two decode GALs (UOPA/UOPB) hold as fuses.</p>\n");
        sb.Append("<div class=scroll><table>\n<thead><tr><th class=lab>IDX</th><th class=lab2>micro-op</th>");
        foreach (var n in MicroOp.DecoderLineNames)
            sb.Append($"<th class=v>{n}</th>");
        sb.Append("</tr></thead><tbody>\n");

        for (int i = 0; i < dict.Count; i++)
        {
            var op = dict.Ops[i];
            var bits = op.DecoderLines();
            sb.Append($"<tr><td class=lab>{i}</td><td class=lab2>{Esc(op.Describe())}</td>");
            for (int b = 0; b < bits.Length; b++)
                sb.Append(bits[b] != 0 ? "<td class='v on'>&nbsp;</td>" : "<td class='v off'>&nbsp;</td>");
            sb.Append("</tr>\n");
        }
        sb.Append("</tbody></table></div>\n");
    }

    // View 2 -----------------------------------------------------------------
    static void SequencerView(StringBuilder sb, Sequencer seq, MicroDictionary dict)
    {
        sb.Append("<h2>2 &middot; Sequencer (Stage 1)</h2>\n");
        sb.Append("<p class=note>Per bank, the micro-op index at each (opcode&#8209;low, T, COND). A dash is a don't-care (halt-filled). Each block is one combinational 22V10; the T-state comes from the external '161 counter. &bull; marks the /TRST step.</p>\n");

        foreach (var bank in seq.Banks)
        {
            sb.Append($"<h3>{bank.Name}</h3>\n");
            sb.Append("<div class=scroll><table class=seq>\n<thead><tr><th class=lab>op</th>");
            for (int t = 0; t < Sequencer.MaxT; t++) sb.Append($"<th class=v>T{t}</th>");
            sb.Append("</tr></thead><tbody>\n");

            if (bank.Alu)
            {
                for (int o = 0; o < 64; o++)
                {
                    bool any = false;
                    for (int t = 0; t < Sequencer.MaxT && !any; t++)
                        if (seq.Alu(o, t).Defined) any = true;
                    if (!any) continue;
                    sb.Append($"<tr><td class=lab>0x{0x40 + o:X2}</td>");
                    for (int t = 0; t < Sequencer.MaxT; t++)
                        AppendCell(sb, seq.Alu(o, t));
                    sb.Append("</tr>\n");
                }
            }
            else
            {
                for (int lo = 0; lo < 16; lo++)
                {
                    bool any = false;
                    for (int t = 0; t < Sequencer.MaxT && !any; t++)
                        for (int c = 0; c < 2; c++)
                            if (seq.Simple(bank.Name, lo, t, c).Defined) any = true;
                    if (!any) continue;

                    bool differs = false;
                    for (int t = 0; t < Sequencer.MaxT; t++)
                        if (seq.Simple(bank.Name, lo, t, 0).Index != seq.Simple(bank.Name, lo, t, 1).Index ||
                            seq.Simple(bank.Name, lo, t, 0).Defined != seq.Simple(bank.Name, lo, t, 1).Defined)
                            differs = true;

                    for (int c = 0; c < 2; c++)
                    {
                        if (c == 1 && !differs) continue;
                        sb.Append($"<tr><td class=lab>0x{bank.Nibble:X}{lo:X}{(differs ? (c == 0 ? " nt" : " tk") : "")}</td>");
                        for (int t = 0; t < Sequencer.MaxT; t++)
                            AppendCell(sb, seq.Simple(bank.Name, lo, t, c));
                        sb.Append("</tr>\n");
                    }
                }
            }
            sb.Append("</tbody></table></div>\n");
        }

        sb.Append("<h3>ENTRY (INTP)</h3>\n<div class=scroll><table class=seq>\n<thead><tr>");
        for (int t = 0; t < Sequencer.MaxT; t++) sb.Append($"<th class=v>T{t}</th>");
        sb.Append("</tr></thead><tbody><tr>");
        for (int t = 0; t < Sequencer.MaxT; t++)
            AppendCell(sb, seq.EntryAt(t));
        sb.Append("</tr></tbody></table></div>\n");
    }

    static void AppendCell(StringBuilder sb, Sequencer.Cell cell)
    {
        sb.Append(cell.Defined
            ? $"<td class='v idx'>{cell.Index}{(cell.Trst ? "<span class=e>&bull;</span>" : "")}</td>"
            : "<td class='v off'>&ndash;</td>");
    }
    
    // View 3 -----------------------------------------------------------------
    static void InstructionView(StringBuilder sb, IReadOnlyList<Instruction> program, MicroDictionary dict)
    {
        sb.Append("<h2>3 &middot; Instruction &rarr; micro-op sequence</h2>\n");
        sb.Append("<p class=note>Each opcode as its ordered list of dictionary indices &mdash; the bridge between the two stages. Bracketed sequences are the taken path of a conditional.</p>\n");
        sb.Append("<div class=scroll><table>\n<thead><tr><th class=lab>opcode</th><th class=lab2>mnemonic</th><th class=lab2>T</th><th class=lab3>micro-op sequence (indices)</th></tr></thead><tbody>\n");

        foreach (var ins in program)
        {
            string seqStr = string.Join(" ", ins.Steps.Select(s => dict.Index(s.Op).ToString()));
            string taken = ins.TakenSteps is { } tk
                ? "  [taken: " + string.Join(" ", tk.Select(s => dict.Index(s.Op))) + "]"
                : "";
            sb.Append($"<tr><td class=lab>0x{ins.Opcode:X2}</td><td class=lab2>{Esc(ins.Mnemonic)}</td>" +
                      $"<td class=lab2>{ins.Steps.Count}</td><td class=lab3>{seqStr}{Esc(taken)}</td></tr>\n");
        }
        sb.Append("</tbody></table></div>\n");
    }

    static string Esc(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    static string Head() => """
        <!DOCTYPE html><html lang=en><head><meta charset=utf-8>
        <title>Blinky-M rev 14 Control Reference</title>
        <style>
          body{margin:0;padding:24px 30px 60px;background:#faf8f2;color:#2b2822;
            font:14px/1.5 Georgia,'Times New Roman',serif}
          h1{font-size:23px;margin:0 0 2px}
          h2{font-size:16px;margin:30px 0 6px;border-bottom:2px solid #2b2822;padding-bottom:4px}
          h3{font-size:13px;margin:18px 0 4px;color:#5a5444;font-family:ui-monospace,Consolas,monospace}
          .sub,.note{font-family:ui-monospace,Consolas,monospace;font-size:11.5px;color:#6a655a}
          .note{max-width:900px;margin:2px 0 8px}
          .scroll{overflow:auto;border:1px solid #d8d4c8;background:#fff;max-height:70vh;margin-bottom:8px}
          table{border-collapse:collapse;font-family:ui-monospace,Consolas,monospace;font-size:11px}
          thead th{position:sticky;top:0;background:#ece8dc;border-bottom:2px solid #2b2822;
            padding:4px 5px;font-size:10px;white-space:nowrap}
          th.lab,td.lab{position:sticky;left:0;background:#fff;z-index:2;text-align:left;
            padding:3px 8px;border-right:2px solid #2b2822;white-space:nowrap}
          thead th.lab{background:#ece8dc;z-index:3}
          td.lab2,th.lab2{padding:3px 8px;border-right:1px solid #e4e0d4;white-space:nowrap}
          td.lab3,th.lab3{padding:3px 8px;text-align:left}
          td.v{text-align:center;border-bottom:1px solid #eeeade;border-left:1px solid #f1eee4;
            min-width:22px;padding:3px 3px}
          td.on{background:#3f7d4e}
          td.off{background:#f4f2ec;color:#c9c4b6}
          td.idx{background:#eef3ee;color:#2b4a30}
          .e{color:#7a2b2b;margin-left:2px}
          table.seq td.idx{font-weight:600}
          tbody tr:hover td.v{filter:brightness(.97)}
        </style></head><body>

        """;
}