using System.Text;
using BlinkyMGen;

// ---------------------------------------------------------------------------
// BlinkyMGen — builds the four Blinky-M uROM images (uROM0..uROM3, 28C64 each)
// from the instruction table, plus a human-readable decoded listing.
//
// Usage:  BlinkyMGen <outputFolder>
// Output: uROM0.hex .. uROM3.hex (Intel HEX), listing.txt
// ---------------------------------------------------------------------------

const int RomSize = 8192;                       // 28C64

if (args.Length != 1)
{
    Console.WriteLine("Usage: BlinkyMGen <outputFolder>");
    Console.WriteLine("Writes uROM0.hex .. uROM3.hex (Intel HEX) and listing.txt to the folder.");
    return;
}
string outDir = args[0];
Directory.CreateDirectory(outDir);

var rom = new byte[4][];
for (int i = 0; i < 4; i++) rom[i] = new byte[RomSize];

// uROM address: opcode<<5 | T<<2 | COND<<1 | INTP
static int Addr(int opcode, int t, int cond, int intp)
    => (opcode << 5) | (t << 2) | (cond << 1) | intp;

void Write(int opcode, int t, int cond, int intp, MicroStep s)
{
    int a = Addr(opcode, t, cond, intp);
    rom[0][a] = s.Rom0; rom[1][a] = s.Rom1; rom[2][a] = s.Rom2; rom[3][a] = s.Rom3;
}

// 1) Fill the whole map with the illegal-opcode row: halt visibly.
for (int a = 0; a < RomSize; a++)
{
    var f = InstructionSet.IllegalFill;
    rom[0][a] = f.Rom0; rom[1][a] = f.Rom1; rom[2][a] = f.Rom2; rom[3][a] = f.Rom3;
}

// 2) INTP=1 rows: the hardware-entry microprogram, identical under every
//    opcode (the bypass presents the fetched opcode at T0, but the entry row
//    wins via A0). INTP is registered at the fetch edge, so the sequence
//    cannot be torn when ISET clears the pending condition.
for (int op = 0; op < 256; op++)
    for (int cond = 0; cond < 2; cond++)
        for (int t = 0; t < InstructionSet.Entry.Length; t++)
            Write(op, t, cond, intp: 1, InstructionSet.Entry[t]);

// 3) The instruction table, INTP=0 rows. COND=1 mirrors COND=0 unless the
//    instruction supplies a taken variant (the conditionals).
var used = new HashSet<byte>();
foreach (var ins in InstructionSet.All)
{
    if (!used.Add(ins.Opcode))
        throw new InvalidOperationException($"Duplicate opcode 0x{ins.Opcode:X2} ({ins.Mnemonic})");
    if (ins.Steps.Length > 8 || (ins.StepsCondTrue?.Length ?? 0) > 8)
        throw new InvalidOperationException($"{ins.Mnemonic}: more than 8 T-states");
    if (!ins.Steps[^1].Trst || (ins.StepsCondTrue is { } ct && !ct[^1].Trst))
        throw new InvalidOperationException($"{ins.Mnemonic}: last step must assert TRST");

    for (int t = 0; t < ins.Steps.Length; t++)
        Write(ins.Opcode, t, cond: 0, intp: 0, ins.Steps[t]);

    var taken = ins.StepsCondTrue ?? ins.Steps;
    for (int t = 0; t < taken.Length; t++)
        Write(ins.Opcode, t, cond: 1, intp: 0, taken[t]);
}

// 4) Emit.
for (int i = 0; i < 4; i++)
    File.WriteAllText(Path.Combine(outDir, $"uROM{i}.hex"), IntelHex.Emit(rom[i]));

File.WriteAllText(Path.Combine(outDir, "listing.txt"), BuildListing());
Console.WriteLine($"Wrote uROM0..uROM3.hex + listing.txt to {Path.GetFullPath(outDir)}");
Console.WriteLine($"{used.Count} opcodes assigned, {256 - used.Count} halt-filled.");
return;

// ---------------------------------------------------------------------------

string BuildListing()
{
    var sb = new StringBuilder();
    sb.AppendLine("Blinky-M uROM listing — generated by BlinkyMGen");
    sb.AppendLine("Fields: SRC>DST @ADDR | ALU | PC | DSP RSP | TOS | flags | I | /TRST (asserted low)");
    sb.AppendLine();

    foreach (var ins in InstructionSet.All.OrderBy(i => i.Opcode))
    {
        sb.AppendLine($"0x{ins.Opcode:X2}  {ins.Mnemonic} {ins.Operand}  — {ins.Steps.Length} T"
            + (ins.StepsCondTrue is { } ct ? $" not taken / {ct.Length} T taken" : ""));
        Dump(sb, ins.Steps, ins.StepsCondTrue is null ? "" : "  [COND=0]");
        if (ins.StepsCondTrue is { } tk) Dump(sb, tk, "  [COND=1]");
        sb.AppendLine();
    }

    sb.AppendLine("(INTP=1)  hardware entry — shared by every opcode — "
        + $"{InstructionSet.Entry.Length} T");
    Dump(sb, InstructionSet.Entry, "");
    return sb.ToString();
}

static void Dump(StringBuilder sb, MicroStep[] steps, string tag)
{
    if (tag.Length > 0) sb.AppendLine(tag);
    for (int t = 0; t < steps.Length; t++)
    {
        var s = steps[t];
        var p = new List<string>();

        if (s.Src != Src.None || s.Dst != Dst.None)
            p.Add($"{s.Src}>{s.Dst} @{AddrName(s)}");
        if (s.Src == Src.Alu || s.NzWe) p.Add($"ALU[{Convert.ToString(s.Rom1 & 0x3F, 2).PadLeft(6, '0')}]");
        if (s.PcInc) p.Add("PC++");
        if (s.PcHiByte) p.Add("PCB=hi");
        if (s.Dsp != SpOp.Hold) p.Add($"DSP{(s.Dsp == SpOp.Up ? "++" : "--")}");
        if (s.Rsp != SpOp.Hold) p.Add($"RSP{(s.Rsp == SpOp.Up ? "++" : "--")}");
        if (s.Tos != TosMode.Hold) p.Add($"TOS:{s.Tos}");
        if (s.NzWe) p.Add("NZ_WE");
        if (s.CWe) p.Add("C_WE");
        if (s.ISet) p.Add("I=1");
        if (s.IClr) p.Add("I=0");
        if (s.Trst) p.Add("/TRST");

        sb.AppendLine($"  T{t}  {string.Join("  ", p)}");
    }
}

static string AddrName(MicroStep s) => s.Asel switch
{
    Asel.Pc => "PC",
    Asel.Adr => "ADR",
    Asel.PgSp => $"{{{(int)s.Pg:X2},{(s.SpSelRsp ? "RSP" : "DSP")}}}",
    _ => $"{{{(int)s.Pg:X2},ADRlo}}",
};